$NetBSD$

Relax MSRV.

--- yazi-shared/Cargo.toml.orig	2026-01-23 07:21:01.546582420 +0000
+++ yazi-shared/Cargo.toml
@@ -7,7 +7,7 @@ repository   = "https://github.com/sxyazi/yazi"
 description  = "Yazi shared library"
 homepage     = "https://yazi-rs.github.io"
 repository   = "https://github.com/sxyazi/yazi"
-rust-version = "1.92.0"
+rust-version = "1.91.0"
 
 [lints]
 workspace = true
