$NetBSD$

--- pyproject.toml.orig	2026-02-21 09:22:55.894229090 +0000
+++ pyproject.toml
@@ -6,7 +6,7 @@ requires-python = ">=3.9"
 license = { text = "Apache Software License" }
 authors = [{ name = "Andrey Kislyuk"}, {email = "kislyuk@gmail.com" }]
 maintainers = [{ name = "Andrey Kislyuk"}, {email = "kislyuk@gmail.com" }]
-dynamic = ["version"]
+version = "4.3.1"
 classifiers = [
   "Intended Audience :: Developers",
   "License :: OSI Approved :: Apache Software License",
