$NetBSD$

--- syncserver/Cargo.toml.orig	2022-12-16 18:15:37.000000000 +0000
+++ syncserver/Cargo.toml
@@ -26,7 +26,7 @@ chrono = "0.4"
 # Pin to 0.5 for now, to keep it under tokio 0.2 (issue977).
 # Fix for #803 (deadpool#92) points to our fork for now
 #deadpool = "0.5"  # pin to 0.5
-deadpool = { git = "https://github.com/mozilla-services/deadpool", branch = "deadpool-v0.5.2-issue92" }
+deadpool = { path = "../deadpool" }
 diesel = { version = "1.4", features = ["mysql", "r2d2"] }
 diesel_logger = "0.1.1"
 diesel_migrations = { version = "1.4.0", features = ["mysql"] }
