$NetBSD$

Unconditionally use libc, also needed on NetBSD.

--- process-hardening/Cargo.toml.orig	2025-11-10 10:14:13.915189238 +0000
+++ process-hardening/Cargo.toml
@@ -11,11 +11,4 @@ path = "src/lib.rs"
 workspace = true
 
 [dependencies]
-[target.'cfg(target_os = "linux")'.dependencies]
-libc = { workspace = true }
-
-[target.'cfg(target_os = "android")'.dependencies]
-libc = { workspace = true }
-
-[target.'cfg(target_os = "macos")'.dependencies]
 libc = { workspace = true }
