$NetBSD$

--- syncstorage-spanner/Cargo.toml.orig	2023-06-10 19:04:16.000000000 +0000
+++ syncstorage-spanner/Cargo.toml
@@ -10,7 +10,7 @@ cadence = "0.26"
 # Pin to 0.5 for now, to keep it under tokio 0.2 (issue977).
 # Fix for #803 (deadpool#92) points to our fork for now
 #deadpool = "0.5"  # pin to 0.5
-deadpool = { git = "https://github.com/mozilla-services/deadpool", branch = "deadpool-v0.5.2-issue92" }
+deadpool = { path = "../../deadpool" }
 env_logger = "0.9"
 futures = { version = "0.3", features = ["compat"] }
 google-cloud-rust-raw = "0.11.0"
