$NetBSD$

Relax MSRV.

--- Cargo.toml.orig	2026-01-05 06:33:03.436515055 +0000
+++ Cargo.toml
@@ -4,7 +4,7 @@ resolver = "2"
 resolver = "2"
 
 [workspace.package]
-rust-version = "1.92"
+rust-version = "1.90"
 version = "0.7.9"
 edition = "2024"
 authors = ["ds1sqe(dukim) <ds1sqe@mensakorea.org>"]
