$NetBSD$

Relax MSRV.

--- Cargo.toml.orig	2026-01-15 08:16:16.078473330 +0000
+++ Cargo.toml
@@ -29,7 +29,7 @@ resolver = "2"
 resolver = "2"
 
 [workspace.package]
-rust-version = "1.92"
+rust-version = "1.91"
 version = "0.8.1"
 edition = "2024"
 authors = ["ds1sqe(dukim) <ds1sqe@mensakorea.org>"]
